using System.Text;
using System.Text.Json;

namespace KeyCassTrompete;

public class KeymapConfig
{
    public Dictionary<string, string> keymap { get; set; } = new();
}

public static class TemplateProcessor
{
    public static void Run()
    {
        Console.WriteLine("=== Template Processor ===");
        Console.WriteLine("Processando keymap.c.template...\n");

        string templatePath = "keymaps/default/keymap.c.template";
        string outputPath = "keymaps/default/keymap.c";
        string keymapPath = "config/keymap.json";

        if (!File.Exists(templatePath))
        {
            Console.WriteLine($"Erro: Template nao encontrado em {templatePath}");
            return;
        }

        try
        {
            string keymapJson = File.ReadAllText(keymapPath);
            var keymapConfig = JsonSerializer.Deserialize<KeymapConfig>(keymapJson);

            if (keymapConfig?.keymap == null)
            {
                Console.WriteLine("Erro: Formato de keymap.json invalido");
                return;
            }

            var validEntries = keymapConfig.keymap
                .Where(entry => !string.IsNullOrEmpty(entry.Value));

            var singleKeys = validEntries
                .Where(entry => !entry.Key.Contains('_'))
                .Select(entry => entry.Value)
                .ToList();

            var comboEntries = validEntries
                .Where(entry => entry.Key.Contains('_'))
                .ToList();

            var comboDefsBuilder = new StringBuilder();
            var combosBuilder = new StringBuilder();

            foreach (var entry in comboEntries)
            {
                var keys = entry.Key.Split('_');

                var comboKeys = keys
                    .Select(k => keymapConfig.keymap[k])
                    .ToList();

                comboDefsBuilder.AppendLine(
                    $"const uint16_t PROGMEM combo_{entry.Key}[] = {{ {string.Join(", ", comboKeys)}, COMBO_END }};"
                );

                combosBuilder.AppendLine($"    COMBO(combo_{entry.Key}, {entry.Value}),");
            }

            string content = File.ReadAllText(templatePath);

            // StringBuilder também pode ser usado para construir strings complexas
            var headerBuilder = new StringBuilder();
            headerBuilder.AppendLine("// File generated by TemplateProcessor.cs");
            headerBuilder.AppendLine($"// Generated on {DateTime.Now:dd/MM/yyyy HH:mm:ss}");
            headerBuilder.AppendLine("// Run: dotnet run build");
            headerBuilder.AppendLine();

            content = headerBuilder.ToString() + content;

            // Substituições no template
            content = content.Replace("{{COMBOS_DEF}}", comboDefsBuilder.ToString().TrimEnd());
            content = content.Replace("{{LAYOUT}}", string.Join(", ", singleKeys));
            content = content.Replace("{{COMBOS}}", combosBuilder.ToString().TrimEnd());

            // Escreve o arquivo de saída
            File.WriteAllText(outputPath, content);

            Console.WriteLine($"Substituicoes realizadas:");
            Console.WriteLine($"  - {singleKeys.Count} teclas simples");
            Console.WriteLine($"  - {comboEntries.Count} combos");
            Console.WriteLine($"  - Total: {keymapConfig.keymap.Count} keys processadas");
            Console.WriteLine();
            Console.WriteLine($"Arquivo gerado com sucesso: {outputPath}");
            Console.WriteLine($"Tamanho: {content.Length} bytes");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Erro ao processar template: {ex.Message}");
        }
    }
}
