using System.Text.Json;

namespace KeyCassTrompete;

public class KeymapConfig
{
    public Dictionary<string, string> keymap { get; set; } = new();
}

public static class TemplateProcessor
{
    public static void Run()
    {
        Console.WriteLine("=== Template Processor ===");
        Console.WriteLine("Processando keymap.c.template...\n");

        string templatePath = "keymaps/default/keymap.c.template";
        string outputPath = "keymaps/default/keymap.c";

        string keymapPath = "config/keymap.json";

        if (!File.Exists(templatePath))
        {
            Console.WriteLine($"Erro: Template nao encontrado em {templatePath}");
            return;
        }

        try
        {
            string keymapJson = File.ReadAllText(keymapPath);
            var keymapConfig = JsonSerializer.Deserialize<KeymapConfig>(keymapJson);

            if (keymapConfig?.keymap == null)
            {
                Console.WriteLine("Erro: Formato de keymap.json invalido");
                return;
            }

            string comboDefs = "";
            List<string> layout = [];
            List<string> combos = [];
            foreach (var entry in keymapConfig.keymap)
            {
                if (entry.Value == "") {
                    continue;
                }

                string[] keys = entry.Key.Split("_");
                if (keys.Length == 1) {
                    layout.Add(entry.Value);
                    continue;
                }

                List<string> comandBuild = keys.Select(k => keymapConfig.keymap[k]).ToList();
                comboDefs += $"\nconst uint16_t PROGMEM combo_{entry.Key}[] = {"{"} {String.Join(", ", comandBuild)}, COMBO_END {"}"};";

                combos.Add($"COMBO(combo_{entry.Key}, {entry.Value}),");
            }

            // Le o template
            string content = File.ReadAllText(templatePath);
            content = $"// File generated by TemplateProcessor.cs\n// Generated on {DateTime.Now:dd/MM/yyyy HH:mm:ss}\n// Run: dotnet run build\n\n{content}";

            content = content.Replace("{{COMBOS_DEF}}", comboDefs);
            content = content.Replace("{{LAYOUT}}", String.Join(", ", layout));
            content = content.Replace("{{COMBOS}}", String.Join(",\n    ", combos));

            Console.WriteLine($"Substituicoes realizadas: {keymapConfig.keymap.Count} keys processadas");
            Console.WriteLine();

            // Escreve o arquivo de saida
            File.WriteAllText(outputPath, content);

            Console.WriteLine($"Arquivo gerado com sucesso: {outputPath}");
            Console.WriteLine($"Tamanho: {content.Length} bytes");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Erro ao processar template: {ex.Message}");
        }
    }
}
