using System.Text.Json;

namespace KeyCassTrompete;

public class KeymapConfig
{
    public Dictionary<string, string> keymap { get; set; } = new();
}

public static class TemplateProcessor
{
    public static void Run()
    {
        Console.WriteLine("=== Template Processor ===");
        Console.WriteLine("Processando keymap.c.template...\n");

        string templatePath = "keymaps/default/keymap.c.template";
        string outputPath = "keymaps/default/keymap.c";

        string keymapPath = "config/keymap.json";

        if (!File.Exists(templatePath))
        {
            Console.WriteLine($"Erro: Template nao encontrado em {templatePath}");
            return;
        }

        try
        {
            string keymapJson = File.ReadAllText(keymapPath);
            var keymapConfig = JsonSerializer.Deserialize<KeymapConfig>(keymapJson);

            if (keymapConfig?.keymap == null)
            {
                Console.WriteLine("Erro: Formato de keymap.json invalido");
                return;
            }

            // Le o template
            string content = File.ReadAllText(templatePath);
            content = $"// File generated by TemplateProcessor.cs\n// Generated on {DateTime.Now:dd/MM/yyyy HH:mm:ss}\n// Run: dotnet run build\n\n{content}";

            // Aqui voce pode adicionar suas substituicoes
            // Exemplo de uso do keymap:
            foreach (var kv in keymapConfig.keymap)
            {
                string placeholder = $"{{{{{kv.Key}}}}}"; // {{K1}}, {{K2}}, etc
                content = content.Replace(placeholder, kv.Value);
            }

            Console.WriteLine($"Substituicoes realizadas: {keymapConfig.keymap.Count} keys processadas");
            Console.WriteLine();

            // Escreve o arquivo de saida
            File.WriteAllText(outputPath, content);

            Console.WriteLine($"Arquivo gerado com sucesso: {outputPath}");
            Console.WriteLine($"Tamanho: {content.Length} bytes");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Erro ao processar template: {ex.Message}");
        }
    }
}
