// File generated by TemplateProcessor.cs
// Generated on 03/04/2026 03:22:56
// Run: dotnet run build

// Copyright 2023 QMK
// SPDX-License-Identifier: GPL-2.0-or-later

#include QMK_KEYBOARD_H
#include "raw_hid.h"

void raw_hid_receive(uint8_t *data, uint8_t length) {
    // recebe dados do PC se precisar
    // raw_hid_send(data, length); // envia de volta
}

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    uint8_t data[32] = {0};
    data[0] = (keycode >> 8) & 0xFF;  // byte alto
    data[1] = keycode & 0xFF;          // byte baixo
    data[2] = record->event.pressed ? 1 : 0;
    raw_hid_send(data, sizeof(data));
    return false;
}

// Define os combos
// const uint16_t PROGMEM combo_ae[] = {KC_A, KC_E, COMBO_END};

const uint16_t PROGMEM combo_K1_K2[] = { KC_A, KC_E, COMBO_END };
const uint16_t PROGMEM combo_K1_K3[] = { KC_A, KC_O, COMBO_END };
const uint16_t PROGMEM combo_K1_K4[] = { KC_A, KC_I, COMBO_END };
const uint16_t PROGMEM combo_K1_K5[] = { KC_A, KC_SPC, COMBO_END };
const uint16_t PROGMEM combo_K2_K3[] = { KC_E, KC_O, COMBO_END };
const uint16_t PROGMEM combo_K2_K4[] = { KC_E, KC_I, COMBO_END };
const uint16_t PROGMEM combo_K2_K5[] = { KC_E, KC_SPC, COMBO_END };
const uint16_t PROGMEM combo_K3_K4[] = { KC_O, KC_I, COMBO_END };
const uint16_t PROGMEM combo_K3_K5[] = { KC_O, KC_SPC, COMBO_END };
const uint16_t PROGMEM combo_K4_K5[] = { KC_I, KC_SPC, COMBO_END };
const uint16_t PROGMEM combo_K1_K2_K3[] = { KC_A, KC_E, KC_O, COMBO_END };
const uint16_t PROGMEM combo_K1_K2_K4[] = { KC_A, KC_E, KC_I, COMBO_END };
const uint16_t PROGMEM combo_K1_K2_K5[] = { KC_A, KC_E, KC_SPC, COMBO_END };
const uint16_t PROGMEM combo_K1_K3_K4[] = { KC_A, KC_O, KC_I, COMBO_END };
const uint16_t PROGMEM combo_K1_K3_K5[] = { KC_A, KC_O, KC_SPC, COMBO_END };
const uint16_t PROGMEM combo_K1_K4_K5[] = { KC_A, KC_I, KC_SPC, COMBO_END };
const uint16_t PROGMEM combo_K2_K3_K4[] = { KC_E, KC_O, KC_I, COMBO_END };
const uint16_t PROGMEM combo_K2_K3_K5[] = { KC_E, KC_O, KC_SPC, COMBO_END };
const uint16_t PROGMEM combo_K2_K4_K5[] = { KC_E, KC_I, KC_SPC, COMBO_END };
const uint16_t PROGMEM combo_K3_K4_K5[] = { KC_O, KC_I, KC_SPC, COMBO_END };
const uint16_t PROGMEM combo_K1_K2_K3_K4[] = { KC_A, KC_E, KC_O, KC_I, COMBO_END };
const uint16_t PROGMEM combo_K1_K2_K3_K5[] = { KC_A, KC_E, KC_O, KC_SPC, COMBO_END };

combo_t key_combos[] = {
    // COMBO(combo_ae, KC_X),  // A+E together = X
    COMBO(combo_K1_K2, KC_S),,
    COMBO(combo_K1_K3, KC_R),,
    COMBO(combo_K1_K4, KC_D),,
    COMBO(combo_K1_K5, KC_U),,
    COMBO(combo_K2_K3, KC_M),,
    COMBO(combo_K2_K4, KC_N),,
    COMBO(combo_K2_K5, KC_C),,
    COMBO(combo_K3_K4, KC_T),,
    COMBO(combo_K3_K5, KC_L),,
    COMBO(combo_K4_K5, KC_P),,
    COMBO(combo_K1_K2_K3, KC_B),,
    COMBO(combo_K1_K2_K4, KC_G),,
    COMBO(combo_K1_K2_K5, KC_F),,
    COMBO(combo_K1_K3_K4, KC_V),,
    COMBO(combo_K1_K3_K5, KC_Q),,
    COMBO(combo_K1_K4_K5, KC_J),,
    COMBO(combo_K2_K3_K4, KC_Z),,
    COMBO(combo_K2_K3_K5, KC_H),,
    COMBO(combo_K2_K4_K5, KC_K),,
    COMBO(combo_K3_K4_K5, KC_W),,
    COMBO(combo_K1_K2_K3_K4, KC_X),,
    COMBO(combo_K1_K2_K3_K5, KC_Y),
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    /*
     * ┌───┬───┬───┬───┐
     * │ 7 │ 8 │ 9 │ / │
     * ├───┼───┼───┼───┤
     * │ 4 │ 5 │ 6 │ * │
     * ├───┼───┼───┼───┤
     * │ 1 │ 2 │ 3 │ - │
     * ├───┼───┼───┼───┤
     * │ 0 │ . │Ent│ + │
     * └───┴───┴───┴───┘
     */
    [0] = LAYOUT(
        KC_A, KC_E, KC_O, KC_I, KC_SPC
    )
};
